--Last update: 6/12/2016

local VoidData = {
["PC"] = {
    {"Tower I","Capture","ODONATA","BLUEPRINT"},
    {"Tower I","Capture","PARIS","GRIP"},
    {"Tower I","Capture","FORMA","BLUEPRINT"},
    {"Tower I","Capture","PARIS","STRING"},
    {"Tower I","Capture","LEX","RECEIVER"},
    {"Tower II","Capture","ORTHOS","HANDLE"},
    {"Tower II","Capture","PARIS","STRING"},
    {"Tower II","Capture","FORMA","BLUEPRINT"},
    {"Tower II","Capture","ORTHOS","BLADE"},
    {"Tower II","Capture","VOLT","BLUEPRINT"},
    {"Tower II","Capture","NYX","BLUEPRINT"},
    {"Tower II","Capture","KAVASA","BAND"},
    {"Tower III","Capture","NIKANA","HILT"},
    {"Tower III","Capture","FORMA","BLUEPRINT"},
    {"Tower III","Capture","SPIRA","POUCH"},
    {"Tower III","Capture","DUAL KAMAS","BLADE"},
    {"Tower III","Capture","AKBRONCO","LINK"},
    {"Tower III","Capture","BURSTON","BARREL"},
    {"Tower III","Capture","LEX","BARREL"},
    {"Tower IV","Capture","NYX","SYSTEMS BLUEPRINT"},
    {"Tower IV","Capture","FORMA","BLUEPRINT"},
    {"Tower IV","Capture","BRONCO","RECEIVER"},
    {"Tower IV","Capture","VOLT","BLUEPRINT"},
    {"Tower IV","Capture","AKBRONCO","LINK"},
    {"Tower I","Defense C","VASTO","RECEIVER"},
    {"Tower I","Defense C","CARRIER","SYSTEMS"},
    {"Tower I","Defense C","FORMA","BLUEPRINT"},
    {"Tower I","Defense C","HIKOU","STARS"},
    {"Tower I","Defense C","SCINDO","HANDLE"},
    {"Tower II","Defense A","SOMA","BLUEPRINT"},
    {"Tower II","Defense A","ORTHOS","BLADE"},
    {"Tower II","Defense B","BURSTON","STOCK"},
    {"Tower II","Defense B","PARIS","BLUEPRINT"},
    {"Tower II","Defense C","FANG","HANDLE"},
    {"Tower II","Defense C","BRATON","STOCK"},
    {"Tower II","Defense C","LEX","RECEIVER"},
    {"Tower II","Defense C","PARIS","UPPER LIMB"},
    {"Tower II","Defense C","FANG","BLUEPRINT"},
    {"Tower III","Defense A","TRINITY","CHASSIS BLUEPRINT"},
    {"Tower III","Defense B","LEX","BLUEPRINT"},
    {"Tower III","Defense B","PARIS","STRING"},
    {"Tower III","Defense B","BURSTON","BLUEPRINT"},
    {"Tower III","Defense C","BRATON","BARREL"},
    {"Tower III","Defense C","BRATON","RECEIVER"},
    {"Tower III","Defense C","FORMA","BLUEPRINT"},
    {"Tower III","Defense C","ASH","BLUEPRINT"},
    {"Tower III","Defense C","BRATON","STOCK"},
    {"Tower III","Defense C","NYX","BLUEPRINT"},
    {"Tower III","Defense C","FRAGOR","HANDLE"},
    {"Tower IV","Defense A","FORMA","BLUEPRINT"},
    {"Tower IV","Defense A","LEX","BLUEPRINT"},
    {"Tower IV","Defense A","ORTHOS","HANDLE"},
    {"Tower IV","Defense A","VECTIS","BARREL"},
    {"Tower IV","Defense B","BRATON","BARREL"},
    {"Tower IV","Defense B","BRATON","RECEIVER"},
    {"Tower IV","Defense B","CARRIER","SYSTEMS"},
    {"Tower IV","Defense C","AKSTILETTO","BLUEPRINT"},
    {"Tower IV","Defense C","VAUBAN","CHASSIS BLUEPRINT"},
    {"Tower IV","Defense C","TRINITY","BLUEPRINT"},
    {"Tower IV","Defense C","ODONATA","BLUEPRINT"},
    {"Tower IV","Defense C","CARRIER","CARAPACE"},
    {"Tower IV","Defense C","BURSTON","RECEIVER"},
    {"Tower IV","Defense C","HIKOU","POUCH"},
    {"Tower I","Exterminate","SCINDO","BLUEPRINT"},
    {"Tower I","Exterminate","FRAGOR","BLUEPRINT"},
    {"Tower I","Exterminate","FORMA","BLUEPRINT"},
    {"Tower I","Exterminate","BURSTON","STOCK"},
    {"Tower II","Exterminate","CARRIER","CEREBRUM"},
    {"Tower II","Exterminate","VOLT","HELMET BLUEPRINT"},
    {"Tower II","Exterminate","NOVA","BLUEPRINT"},
    {"Tower II","Exterminate","FORMA","BLUEPRINT"},
    {"Tower II","Exterminate","ORTHOS","BLUEPRINT"},
    {"Tower II","Exterminate","SARYN","SYSTEMS BLUEPRINT"},
    {"Tower II","Exterminate","VOLT","SYSTEMS"},
    {"Tower III","Exterminate","NYX","CHASSIS BLUEPRINT"},
    {"Tower III","Exterminate","SOMA","STOCK"},
    {"Tower III","Exterminate","VASTO","RECEIVER"},
    {"Tower III","Exterminate","NIKANA","BLUEPRINT"},
    {"Tower III","Exterminate","SARYN","BLUEPRINT"},
    {"Tower III","Exterminate","NYX","SYSTEMS BLUEPRINT"},
    {"Tower IV","Exterminate","KAVASA","BUCKLE"},
    {"Tower IV","Exterminate","FORMA","BLUEPRINT"},
    {"Tower IV","Exterminate","ODONATA","HARNESS BLUEPRINT"},
    {"Tower IV","Exterminate","HIKOU","POUCH"},
    {"Tower IV","Exterminate","SARYN","BLUEPRINT"},
    {"Tower IV","Exterminate","VECTIS","RECEIVER"},
    {"Tower IV","Interception A","CARRIER","BLUEPRINT"},
    {"Tower IV","Interception A","AKBRONCO","BLUEPRINT"},
    {"Tower IV","Interception A","KAVASA","COLLAR BLUEPRINT"},
    {"Tower IV","Interception B","VECTIS","BARREL"},
    {"Tower IV","Interception B","HIKOU","BLUEPRINT"},
    {"Tower IV","Interception B","FORMA","BLUEPRINT"},
    {"Tower IV","Interception C","AKSTILETTO","BARREL"},
    {"Tower IV","Interception C","SOMA","BARREL"},
    {"Tower IV","Interception C","FANG","HANDLE"},
    {"Tower IV","Interception C","LEX","RECEIVER"},
    {"Tower IV","Interception C","PARIS","GRIP"},
    {"Tower IV","Interception C","BRONCO","BARREL"},
    {"Tower IV","Interception C","FORMA","BLUEPRINT"},
    {"Tower I","Mobile Defense","SARYN","HELMET BLUEPRINT"},
    {"Tower I","Mobile Defense","VECTIS","BLUEPRINT"},
    {"Tower I","Mobile Defense","BRATON","BARREL"},
    {"Tower I","Mobile Defense","FORMA","BLUEPRINT"},
    {"Tower II","Mobile Defense","BURSTON","BLUEPRINT"},
    {"Tower II","Mobile Defense","NYX","HELMET BLUEPRINT"},
    {"Tower II","Mobile Defense","VASTO","BLUEPRINT"},
    {"Tower II","Mobile Defense","BRATON","BLUEPRINT"},
    {"Tower II","Mobile Defense","VASTO","BARREL"},
    {"Tower II","Mobile Defense","SPIRA","BLUEPRINT"},
    {"Tower III","Mobile Defense","VECTIS","STOCK"},
    {"Tower III","Mobile Defense","TRINITY","SYSTEMS BLUEPRINT"},
    {"Tower III","Mobile Defense","SCINDO","BLADE"},
    {"Tower III","Mobile Defense","FORMA","BLUEPRINT"},
    {"Tower III","Mobile Defense","SPIRA","BLADE"},
    {"Tower III","Mobile Defense","SOMA","BARREL"},
    {"Tower III","Mobile Defense","BURSTON","RECEIVER"},
    {"Tower IV","Mobile Defense","CARRIER","CARAPACE"},
    {"Tower IV","Mobile Defense","KAVASA","COLLAR BLUEPRINT"},
    {"Tower IV","Mobile Defense","VASTO","RECEIVER"},
    {"Tower IV","Mobile Defense","FORMA","BLUEPRINT"},
    {"Tower IV","Mobile Defense","SPIRA","BLUEPRINT"},
    {"Tower I","Sabotage","SCINDO","HANDLE"},
    {"Tower I","Sabotage","ODONATA","HARNESS BLUEPRINT"},
    {"Tower I","Sabotage","HIKOU","STARS"},
    {"Tower I","Sabotage","NOVA","BLUEPRINT"},
    {"Tower I","Sabotage","ODONATA","SYSTEMS BLUEPRINT"},
    {"Tower I","Sabotage","VASTO","BARREL"},
    {"Tower II","Sabotage","NYX","HELMET BLUEPRINT"},
    {"Tower II","Sabotage","VAUBAN","HELMET BLUEPRINT"},
    {"Tower II","Sabotage","HIKOU","BLUEPRINT"},
    {"Tower II","Sabotage","BRONCO","BLUEPRINT"},
    {"Tower II","Sabotage","VOLT","CHASSIS BLUEPRINT"},
    {"Tower II","Sabotage","HIKOU","POUCH"},
    {"Tower II","Sabotage","TRINITY","HELMET BLUEPRINT"},
    {"Tower III","Sabotage","NYX","BLUEPRINT"},
    {"Tower III","Sabotage","FORMA","BLUEPRINT"},
    {"Tower III","Sabotage","SCINDO","BLADE"},
    {"Tower III","Sabotage","NOVA","HELMET BLUEPRINT"},
    {"Tower III","Sabotage","BRONCO","BARREL"},
    {"Tower III","Sabotage","SOMA","BARREL"},
    {"Tower III","Sabotage","VAUBAN","BLUEPRINT"},
    {"Tower III","Sabotage","FORMA",""},
    {"Tower IV","Sabotage","AKSTILETTO","RECEIVER"},
    {"Tower IV","Sabotage","NYX","SYSTEMS BLUEPRINT"},
    {"Tower IV","Sabotage","CARRIER","SYSTEMS"},
    {"Tower IV","Sabotage","FORMA","BLUEPRINT"},
    {"Tower IV","Sabotage","FRAGOR","HEAD"},
    {"Tower IV","Sabotage","KAVASA","BAND"},
    {"Tower IV","Sabotage","ASH","HELMET BLUEPRINT"},
    {"Tower IV","Sabotage","NOVA","HELMET BLUEPRINT"},
    {"Tower I","Survival A","BURSTON","BARREL"},
    {"Tower I","Survival A","ODONATA","SYSTEMS BLUEPRINT"},
    {"Tower I","Survival C","SCINDO","HANDLE"},
    {"Tower I","Survival C","PARIS","UPPER LIMB"},
    {"Tower I","Survival C","VOLT","SYSTEMS BLUEPRINT"},
    {"Tower I","Survival C","PARIS","LOWER LIMB"},
    {"Tower I","Survival C","BURSTON","STOCK"},
    {"Tower I","Survival C","NOVA","HELMET BLUEPRINT"},
    {"Tower II","Survival A","AKBRONCO","BLUEPRINT"},
    {"Tower II","Survival A","PARIS","LOWER LIMB"},
    {"Tower II","Survival A","FORMA","BLUEPRINT"},
    {"Tower II","Survival B","SOMA","BLUEPRINT"},
    {"Tower II","Survival B","FANG","BLADE"},
    {"Tower II","Survival B","HIKOU","BLUEPRINT"},
    {"Tower II","Survival C","BURSTON","RECEIVER"},
    {"Tower II","Survival C","SOMA","RECEIVER"},
    {"Tower II","Survival C","PARIS","BLUEPRINT"},
    {"Tower II","Survival C","ASH","CHASSIS BLUEPRINT"},
    {"Tower II","Survival C","NIKANA","BLADE"},
    {"Tower II","Survival C","BRONCO","BLUEPRINT"},
    {"Tower II","Survival C","TRINITY","CHASSIS BLUEPRINT"},
    {"Tower III","Survival A","FANG","BLUEPRINT"},
    {"Tower III","Survival A","FANG","BLADE"},
    {"Tower III","Survival B","VECTIS","BARREL"},
    {"Tower III","Survival B","LEX","BARREL"},
    {"Tower III","Survival B","VOLT","HELMET BLUEPRINT"},
    {"Tower III","Survival C","LEX","BLUEPRINT"},
    {"Tower III","Survival C","CARRIER","BLUEPRINT"},
    {"Tower III","Survival C","VAUBAN","SYSTEMS BLUEPRINT"},
    {"Tower III","Survival C","ASH","SYSTEMS BLUEPRINT"},
    {"Tower III","Survival C","SARYN","CHASSIS BLUEPRINT"},
    {"Tower III","Survival C","DUAL KAMAS","BLUEPRINT"},
    {"Tower III","Survival C","NOVA","CHASSIS BLUEPRINT"},
    {"Tower III","Survival C","FORMA",""},
    {"Tower IV","Survival A","ASH","CHASSIS BLUEPRINT"},
    {"Tower IV","Survival A","DUAL KAMAS","BLUEPRINT"},
    {"Tower IV","Survival B","ORTHOS","BLUEPRINT"},
    {"Tower IV","Survival B","BRONCO","RECEIVER"},
    {"Tower IV","Survival B","LEX","BARREL"},
    {"Tower IV","Survival C","AKSTILETTO","LINK"},
    {"Tower IV","Survival C","BRATON","BLUEPRINT"},
    {"Tower IV","Survival C","FORMA","BLUEPRINT"},
    {"Tower IV","Survival C","ODONATA","WINGS BLUEPRINT"},
    {"Tower IV","Survival C","VASTO","BLUEPRINT"},
    {"Tower IV","Survival C","ASH","HELMET BLUEPRINT"},
    {"Derelict","Defense C","TRINITY","BLUEPRINT"},
    {"Derelict","Defense C","DUAL KAMAS","HANDLE"},
    {"Derelict","Defense C","SOMA","STOCK"},
    {"Derelict","Defense C","FORMA","BLUEPRINT"},
    {"Derelict","Survival C","BURSTON","BARREL"},
    {"Derelict","Survival C","NOVA","SYSTEMS BLUEPRINT"},
    {"Derelict","Survival C","FORMA","BLUEPRINT"},
},
["PS4"] = {
    {"Tower I","Capture","ODONATA","BLUEPRINT"},
    {"Tower I","Capture","PARIS","GRIP"},
    {"Tower I","Capture","FORMA","BLUEPRINT"},
    {"Tower I","Capture","PARIS","STRING"},
    {"Tower I","Capture","LEX","RECEIVER"},
    {"Tower II","Capture","ORTHOS","HANDLE"},
    {"Tower II","Capture","PARIS","STRING"},
    {"Tower II","Capture","FORMA","BLUEPRINT"},
    {"Tower II","Capture","ORTHOS","BLADE"},
    {"Tower II","Capture","VOLT","BLUEPRINT"},
    {"Tower II","Capture","NYX","BLUEPRINT"},
    {"Tower II","Capture","KAVASA","BAND"},
    {"Tower III","Capture","NIKANA","HILT"},
    {"Tower III","Capture","FORMA","BLUEPRINT"},
    {"Tower III","Capture","SPIRA","POUCH"},
    {"Tower III","Capture","DUAL KAMAS","BLADE"},
    {"Tower III","Capture","AKBRONCO","LINK"},
    {"Tower III","Capture","BURSTON","BARREL"},
    {"Tower III","Capture","LEX","BARREL"},
    {"Tower IV","Capture","NYX","SYSTEMS BLUEPRINT"},
    {"Tower IV","Capture","FORMA","BLUEPRINT"},
    {"Tower IV","Capture","BRONCO","RECEIVER"},
    {"Tower IV","Capture","VOLT","BLUEPRINT"},
    {"Tower IV","Capture","AKBRONCO","LINK"},
    {"Tower I","Defense C","VASTO","RECEIVER"},
    {"Tower I","Defense C","CARRIER","SYSTEMS"},
    {"Tower I","Defense C","FORMA","BLUEPRINT"},
    {"Tower I","Defense C","HIKOU","STARS"},
    {"Tower I","Defense C","SCINDO","HANDLE"},
    {"Tower II","Defense A","SOMA","BLUEPRINT"},
    {"Tower II","Defense A","ORTHOS","BLADE"},
    {"Tower II","Defense B","BURSTON","STOCK"},
    {"Tower II","Defense B","PARIS","BLUEPRINT"},
    {"Tower II","Defense C","FANG","HANDLE"},
    {"Tower II","Defense C","BRATON","STOCK"},
    {"Tower II","Defense C","LEX","RECEIVER"},
    {"Tower II","Defense C","PARIS","UPPER LIMB"},
    {"Tower II","Defense C","FANG","BLUEPRINT"},
    {"Tower III","Defense A","TRINITY","CHASSIS BLUEPRINT"},
    {"Tower III","Defense B","LEX","BLUEPRINT"},
    {"Tower III","Defense B","PARIS","STRING"},
    {"Tower III","Defense B","BURSTON","BLUEPRINT"},
    {"Tower III","Defense C","BRATON","BARREL"},
    {"Tower III","Defense C","BRATON","RECEIVER"},
    {"Tower III","Defense C","FORMA","BLUEPRINT"},
    {"Tower III","Defense C","ASH","BLUEPRINT"},
    {"Tower III","Defense C","BRATON","STOCK"},
    {"Tower III","Defense C","NYX","BLUEPRINT"},
    {"Tower III","Defense C","FRAGOR","HANDLE"},
    {"Tower IV","Defense A","FORMA","BLUEPRINT"},
    {"Tower IV","Defense A","LEX","BLUEPRINT"},
    {"Tower IV","Defense A","ORTHOS","HANDLE"},
    {"Tower IV","Defense A","VECTIS","BARREL"},
    {"Tower IV","Defense B","BRATON","BARREL"},
    {"Tower IV","Defense B","BRATON","RECEIVER"},
    {"Tower IV","Defense B","CARRIER","SYSTEMS"},
    {"Tower IV","Defense C","AKSTILETTO","BLUEPRINT"},
    {"Tower IV","Defense C","VAUBAN","CHASSIS BLUEPRINT"},
    {"Tower IV","Defense C","TRINITY","BLUEPRINT"},
    {"Tower IV","Defense C","ODONATA","BLUEPRINT"},
    {"Tower IV","Defense C","CARRIER","CARAPACE"},
    {"Tower IV","Defense C","BURSTON","RECEIVER"},
    {"Tower IV","Defense C","HIKOU","POUCH"},
    {"Tower I","Exterminate","SCINDO","BLUEPRINT"},
    {"Tower I","Exterminate","FRAGOR","BLUEPRINT"},
    {"Tower I","Exterminate","FORMA","BLUEPRINT"},
    {"Tower I","Exterminate","BURSTON","STOCK"},
    {"Tower II","Exterminate","CARRIER","CEREBRUM"},
    {"Tower II","Exterminate","VOLT","HELMET BLUEPRINT"},
    {"Tower II","Exterminate","NOVA","BLUEPRINT"},
    {"Tower II","Exterminate","FORMA","BLUEPRINT"},
    {"Tower II","Exterminate","ORTHOS","BLUEPRINT"},
    {"Tower II","Exterminate","SARYN","SYSTEMS BLUEPRINT"},
    {"Tower II","Exterminate","VOLT","SYSTEMS"},
    {"Tower III","Exterminate","NYX","CHASSIS BLUEPRINT"},
    {"Tower III","Exterminate","SOMA","STOCK"},
    {"Tower III","Exterminate","VASTO","RECEIVER"},
    {"Tower III","Exterminate","NIKANA","BLUEPRINT"},
    {"Tower III","Exterminate","SARYN","BLUEPRINT"},
    {"Tower III","Exterminate","NYX","SYSTEMS BLUEPRINT"},
    {"Tower IV","Exterminate","KAVASA","BUCKLE"},
    {"Tower IV","Exterminate","FORMA","BLUEPRINT"},
    {"Tower IV","Exterminate","ODONATA","HARNESS BLUEPRINT"},
    {"Tower IV","Exterminate","HIKOU","POUCH"},
    {"Tower IV","Exterminate","SARYN","BLUEPRINT"},
    {"Tower IV","Exterminate","VECTIS","RECEIVER"},
    {"Tower IV","Interception A","CARRIER","BLUEPRINT"},
    {"Tower IV","Interception A","AKBRONCO","BLUEPRINT"},
    {"Tower IV","Interception A","KAVASA","COLLAR BLUEPRINT"},
    {"Tower IV","Interception B","VECTIS","BARREL"},
    {"Tower IV","Interception B","HIKOU","BLUEPRINT"},
    {"Tower IV","Interception B","FORMA","BLUEPRINT"},
    {"Tower IV","Interception C","AKSTILETTO","BARREL"},
    {"Tower IV","Interception C","SOMA","BARREL"},
    {"Tower IV","Interception C","FANG","HANDLE"},
    {"Tower IV","Interception C","LEX","RECEIVER"},
    {"Tower IV","Interception C","PARIS","GRIP"},
    {"Tower IV","Interception C","BRONCO","BARREL"},
    {"Tower IV","Interception C","FORMA","BLUEPRINT"},
    {"Tower I","Mobile Defense","SARYN","HELMET BLUEPRINT"},
    {"Tower I","Mobile Defense","VECTIS","BLUEPRINT"},
    {"Tower I","Mobile Defense","BRATON","BARREL"},
    {"Tower I","Mobile Defense","FORMA","BLUEPRINT"},
    {"Tower II","Mobile Defense","BURSTON","BLUEPRINT"},
    {"Tower II","Mobile Defense","NYX","HELMET BLUEPRINT"},
    {"Tower II","Mobile Defense","VASTO","BLUEPRINT"},
    {"Tower II","Mobile Defense","BRATON","BLUEPRINT"},
    {"Tower II","Mobile Defense","VASTO","BARREL"},
    {"Tower II","Mobile Defense","SPIRA","BLUEPRINT"},
    {"Tower III","Mobile Defense","VECTIS","STOCK"},
    {"Tower III","Mobile Defense","TRINITY","SYSTEMS BLUEPRINT"},
    {"Tower III","Mobile Defense","SCINDO","BLADE"},
    {"Tower III","Mobile Defense","FORMA","BLUEPRINT"},
    {"Tower III","Mobile Defense","SPIRA","BLADE"},
    {"Tower III","Mobile Defense","SOMA","BARREL"},
    {"Tower III","Mobile Defense","BURSTON","RECEIVER"},
    {"Tower IV","Mobile Defense","CARRIER","CARAPACE"},
    {"Tower IV","Mobile Defense","KAVASA","COLLAR BLUEPRINT"},
    {"Tower IV","Mobile Defense","VASTO","RECEIVER"},
    {"Tower IV","Mobile Defense","FORMA","BLUEPRINT"},
    {"Tower IV","Mobile Defense","SPIRA","BLUEPRINT"},
    {"Tower I","Sabotage","SCINDO","HANDLE"},
    {"Tower I","Sabotage","ODONATA","HARNESS BLUEPRINT"},
    {"Tower I","Sabotage","HIKOU","STARS"},
    {"Tower I","Sabotage","NOVA","BLUEPRINT"},
    {"Tower I","Sabotage","ODONATA","SYSTEMS BLUEPRINT"},
    {"Tower I","Sabotage","VASTO","BARREL"},
    {"Tower II","Sabotage","NYX","HELMET BLUEPRINT"},
    {"Tower II","Sabotage","VAUBAN","HELMET BLUEPRINT"},
    {"Tower II","Sabotage","HIKOU","BLUEPRINT"},
    {"Tower II","Sabotage","BRONCO","BLUEPRINT"},
    {"Tower II","Sabotage","VOLT","CHASSIS BLUEPRINT"},
    {"Tower II","Sabotage","HIKOU","POUCH"},
    {"Tower II","Sabotage","TRINITY","HELMET BLUEPRINT"},
    {"Tower III","Sabotage","NYX","BLUEPRINT"},
    {"Tower III","Sabotage","FORMA","BLUEPRINT"},
    {"Tower III","Sabotage","SCINDO","BLADE"},
    {"Tower III","Sabotage","NOVA","HELMET BLUEPRINT"},
    {"Tower III","Sabotage","BRONCO","BARREL"},
    {"Tower III","Sabotage","SOMA","BARREL"},
    {"Tower III","Sabotage","VAUBAN","BLUEPRINT"},
    {"Tower III","Sabotage","FORMA",""},
    {"Tower IV","Sabotage","AKSTILETTO","RECEIVER"},
    {"Tower IV","Sabotage","NYX","SYSTEMS BLUEPRINT"},
    {"Tower IV","Sabotage","CARRIER","SYSTEMS"},
    {"Tower IV","Sabotage","FORMA","BLUEPRINT"},
    {"Tower IV","Sabotage","FRAGOR","HEAD"},
    {"Tower IV","Sabotage","KAVASA","BAND"},
    {"Tower IV","Sabotage","ASH","HELMET BLUEPRINT"},
    {"Tower IV","Sabotage","NOVA","HELMET BLUEPRINT"},
    {"Tower I","Survival A","BURSTON","BARREL"},
    {"Tower I","Survival A","ODONATA","SYSTEMS BLUEPRINT"},
    {"Tower I","Survival C","SCINDO","HANDLE"},
    {"Tower I","Survival C","PARIS","UPPER LIMB"},
    {"Tower I","Survival C","VOLT","SYSTEMS BLUEPRINT"},
    {"Tower I","Survival C","PARIS","LOWER LIMB"},
    {"Tower I","Survival C","BURSTON","STOCK"},
    {"Tower I","Survival C","NOVA","HELMET BLUEPRINT"},
    {"Tower II","Survival A","AKBRONCO","BLUEPRINT"},
    {"Tower II","Survival A","PARIS","LOWER LIMB"},
    {"Tower II","Survival A","FORMA","BLUEPRINT"},
    {"Tower II","Survival B","SOMA","BLUEPRINT"},
    {"Tower II","Survival B","FANG","BLADE"},
    {"Tower II","Survival B","HIKOU","BLUEPRINT"},
    {"Tower II","Survival C","BURSTON","RECEIVER"},
    {"Tower II","Survival C","SOMA","RECEIVER"},
    {"Tower II","Survival C","PARIS","BLUEPRINT"},
    {"Tower II","Survival C","ASH","CHASSIS BLUEPRINT"},
    {"Tower II","Survival C","NIKANA","BLADE"},
    {"Tower II","Survival C","BRONCO","BLUEPRINT"},
    {"Tower II","Survival C","TRINITY","CHASSIS BLUEPRINT"},
    {"Tower III","Survival A","FANG","BLUEPRINT"},
    {"Tower III","Survival A","FANG","BLADE"},
    {"Tower III","Survival B","VECTIS","BARREL"},
    {"Tower III","Survival B","LEX","BARREL"},
    {"Tower III","Survival B","VOLT","HELMET BLUEPRINT"},
    {"Tower III","Survival C","LEX","BLUEPRINT"},
    {"Tower III","Survival C","CARRIER","BLUEPRINT"},
    {"Tower III","Survival C","VAUBAN","SYSTEMS BLUEPRINT"},
    {"Tower III","Survival C","ASH","SYSTEMS BLUEPRINT"},
    {"Tower III","Survival C","SARYN","CHASSIS BLUEPRINT"},
    {"Tower III","Survival C","DUAL KAMAS","BLUEPRINT"},
    {"Tower III","Survival C","NOVA","CHASSIS BLUEPRINT"},
    {"Tower III","Survival C","FORMA",""},
    {"Tower IV","Survival A","ASH","CHASSIS BLUEPRINT"},
    {"Tower IV","Survival A","DUAL KAMAS","BLUEPRINT"},
    {"Tower IV","Survival B","ORTHOS","BLUEPRINT"},
    {"Tower IV","Survival B","BRONCO","RECEIVER"},
    {"Tower IV","Survival B","LEX","BARREL"},
    {"Tower IV","Survival C","AKSTILETTO","LINK"},
    {"Tower IV","Survival C","BRATON","BLUEPRINT"},
    {"Tower IV","Survival C","FORMA","BLUEPRINT"},
    {"Tower IV","Survival C","ODONATA","WINGS BLUEPRINT"},
    {"Tower IV","Survival C","VASTO","BLUEPRINT"},
    {"Tower IV","Survival C","ASH","HELMET BLUEPRINT"},
    {"Derelict","Defense C","TRINITY","BLUEPRINT"},
    {"Derelict","Defense C","DUAL KAMAS","HANDLE"},
    {"Derelict","Defense C","SOMA","STOCK"},
    {"Derelict","Defense C","FORMA","BLUEPRINT"},
    {"Derelict","Survival C","BURSTON","BARREL"},
    {"Derelict","Survival C","NOVA","SYSTEMS BLUEPRINT"},
    {"Derelict","Survival C","FORMA","BLUEPRINT"},
},
["XB1"] = {
    {"Tower I","Capture","ODONATA","BLUEPRINT"},
    {"Tower I","Capture","PARIS","GRIP"},
    {"Tower I","Capture","FORMA","BLUEPRINT"},
    {"Tower I","Capture","PARIS","STRING"},
    {"Tower I","Capture","LEX","RECEIVER"},
    {"Tower II","Capture","ORTHOS","HANDLE"},
    {"Tower II","Capture","PARIS","STRING"},
    {"Tower II","Capture","FORMA","BLUEPRINT"},
    {"Tower II","Capture","ORTHOS","BLADE"},
    {"Tower II","Capture","VOLT","BLUEPRINT"},
    {"Tower II","Capture","NYX","BLUEPRINT"},
    {"Tower II","Capture","KAVASA","BAND"},
    {"Tower III","Capture","NIKANA","HILT"},
    {"Tower III","Capture","FORMA","BLUEPRINT"},
    {"Tower III","Capture","SPIRA","POUCH"},
    {"Tower III","Capture","DUAL KAMAS","BLADE"},
    {"Tower III","Capture","AKBRONCO","LINK"},
    {"Tower III","Capture","BURSTON","BARREL"},
    {"Tower III","Capture","LEX","BARREL"},
    {"Tower IV","Capture","NYX","SYSTEMS BLUEPRINT"},
    {"Tower IV","Capture","FORMA","BLUEPRINT"},
    {"Tower IV","Capture","BRONCO","RECEIVER"},
    {"Tower IV","Capture","VOLT","BLUEPRINT"},
    {"Tower IV","Capture","AKBRONCO","LINK"},
    {"Tower I","Defense C","VASTO","RECEIVER"},
    {"Tower I","Defense C","CARRIER","SYSTEMS"},
    {"Tower I","Defense C","FORMA","BLUEPRINT"},
    {"Tower I","Defense C","HIKOU","STARS"},
    {"Tower I","Defense C","SCINDO","HANDLE"},
    {"Tower II","Defense A","SOMA","BLUEPRINT"},
    {"Tower II","Defense A","ORTHOS","BLADE"},
    {"Tower II","Defense B","BURSTON","STOCK"},
    {"Tower II","Defense B","PARIS","BLUEPRINT"},
    {"Tower II","Defense C","FANG","HANDLE"},
    {"Tower II","Defense C","BRATON","STOCK"},
    {"Tower II","Defense C","LEX","RECEIVER"},
    {"Tower II","Defense C","PARIS","UPPER LIMB"},
    {"Tower II","Defense C","FANG","BLUEPRINT"},
    {"Tower III","Defense A","TRINITY","CHASSIS BLUEPRINT"},
    {"Tower III","Defense B","LEX","BLUEPRINT"},
    {"Tower III","Defense B","PARIS","STRING"},
    {"Tower III","Defense B","BURSTON","BLUEPRINT"},
    {"Tower III","Defense C","BRATON","BARREL"},
    {"Tower III","Defense C","BRATON","RECEIVER"},
    {"Tower III","Defense C","FORMA","BLUEPRINT"},
    {"Tower III","Defense C","ASH","BLUEPRINT"},
    {"Tower III","Defense C","BRATON","STOCK"},
    {"Tower III","Defense C","NYX","BLUEPRINT"},
    {"Tower III","Defense C","FRAGOR","HANDLE"},
    {"Tower IV","Defense A","FORMA","BLUEPRINT"},
    {"Tower IV","Defense A","LEX","BLUEPRINT"},
    {"Tower IV","Defense A","ORTHOS","HANDLE"},
    {"Tower IV","Defense A","VECTIS","BARREL"},
    {"Tower IV","Defense B","BRATON","BARREL"},
    {"Tower IV","Defense B","BRATON","RECEIVER"},
    {"Tower IV","Defense B","CARRIER","SYSTEMS"},
    {"Tower IV","Defense C","AKSTILETTO","BLUEPRINT"},
    {"Tower IV","Defense C","VAUBAN","CHASSIS BLUEPRINT"},
    {"Tower IV","Defense C","TRINITY","BLUEPRINT"},
    {"Tower IV","Defense C","ODONATA","BLUEPRINT"},
    {"Tower IV","Defense C","CARRIER","CARAPACE"},
    {"Tower IV","Defense C","BURSTON","RECEIVER"},
    {"Tower IV","Defense C","HIKOU","POUCH"},
    {"Tower I","Exterminate","SCINDO","BLUEPRINT"},
    {"Tower I","Exterminate","FRAGOR","BLUEPRINT"},
    {"Tower I","Exterminate","FORMA","BLUEPRINT"},
    {"Tower I","Exterminate","BURSTON","STOCK"},
    {"Tower II","Exterminate","CARRIER","CEREBRUM"},
    {"Tower II","Exterminate","VOLT","HELMET BLUEPRINT"},
    {"Tower II","Exterminate","NOVA","BLUEPRINT"},
    {"Tower II","Exterminate","FORMA","BLUEPRINT"},
    {"Tower II","Exterminate","ORTHOS","BLUEPRINT"},
    {"Tower II","Exterminate","SARYN","SYSTEMS BLUEPRINT"},
    {"Tower II","Exterminate","VOLT","SYSTEMS"},
    {"Tower III","Exterminate","NYX","CHASSIS BLUEPRINT"},
    {"Tower III","Exterminate","SOMA","STOCK"},
    {"Tower III","Exterminate","VASTO","RECEIVER"},
    {"Tower III","Exterminate","NIKANA","BLUEPRINT"},
    {"Tower III","Exterminate","SARYN","BLUEPRINT"},
    {"Tower III","Exterminate","NYX","SYSTEMS BLUEPRINT"},
    {"Tower IV","Exterminate","KAVASA","BUCKLE"},
    {"Tower IV","Exterminate","FORMA","BLUEPRINT"},
    {"Tower IV","Exterminate","ODONATA","HARNESS BLUEPRINT"},
    {"Tower IV","Exterminate","HIKOU","POUCH"},
    {"Tower IV","Exterminate","SARYN","BLUEPRINT"},
    {"Tower IV","Exterminate","VECTIS","RECEIVER"},
    {"Tower IV","Interception A","CARRIER","BLUEPRINT"},
    {"Tower IV","Interception A","AKBRONCO","BLUEPRINT"},
    {"Tower IV","Interception A","KAVASA","COLLAR BLUEPRINT"},
    {"Tower IV","Interception B","VECTIS","BARREL"},
    {"Tower IV","Interception B","HIKOU","BLUEPRINT"},
    {"Tower IV","Interception B","FORMA","BLUEPRINT"},
    {"Tower IV","Interception C","AKSTILETTO","BARREL"},
    {"Tower IV","Interception C","SOMA","BARREL"},
    {"Tower IV","Interception C","FANG","HANDLE"},
    {"Tower IV","Interception C","LEX","RECEIVER"},
    {"Tower IV","Interception C","PARIS","GRIP"},
    {"Tower IV","Interception C","BRONCO","BARREL"},
    {"Tower IV","Interception C","FORMA","BLUEPRINT"},
    {"Tower I","Mobile Defense","SARYN","HELMET BLUEPRINT"},
    {"Tower I","Mobile Defense","VECTIS","BLUEPRINT"},
    {"Tower I","Mobile Defense","BRATON","BARREL"},
    {"Tower I","Mobile Defense","FORMA","BLUEPRINT"},
    {"Tower II","Mobile Defense","BURSTON","BLUEPRINT"},
    {"Tower II","Mobile Defense","NYX","HELMET BLUEPRINT"},
    {"Tower II","Mobile Defense","VASTO","BLUEPRINT"},
    {"Tower II","Mobile Defense","BRATON","BLUEPRINT"},
    {"Tower II","Mobile Defense","VASTO","BARREL"},
    {"Tower II","Mobile Defense","SPIRA","BLUEPRINT"},
    {"Tower III","Mobile Defense","VECTIS","STOCK"},
    {"Tower III","Mobile Defense","TRINITY","SYSTEMS BLUEPRINT"},
    {"Tower III","Mobile Defense","SCINDO","BLADE"},
    {"Tower III","Mobile Defense","FORMA","BLUEPRINT"},
    {"Tower III","Mobile Defense","SPIRA","BLADE"},
    {"Tower III","Mobile Defense","SOMA","BARREL"},
    {"Tower III","Mobile Defense","BURSTON","RECEIVER"},
    {"Tower IV","Mobile Defense","CARRIER","CARAPACE"},
    {"Tower IV","Mobile Defense","KAVASA","COLLAR BLUEPRINT"},
    {"Tower IV","Mobile Defense","VASTO","RECEIVER"},
    {"Tower IV","Mobile Defense","FORMA","BLUEPRINT"},
    {"Tower IV","Mobile Defense","SPIRA","BLUEPRINT"},
    {"Tower I","Sabotage","SCINDO","HANDLE"},
    {"Tower I","Sabotage","ODONATA","HARNESS BLUEPRINT"},
    {"Tower I","Sabotage","HIKOU","STARS"},
    {"Tower I","Sabotage","NOVA","BLUEPRINT"},
    {"Tower I","Sabotage","ODONATA","SYSTEMS BLUEPRINT"},
    {"Tower I","Sabotage","VASTO","BARREL"},
    {"Tower II","Sabotage","NYX","HELMET BLUEPRINT"},
    {"Tower II","Sabotage","VAUBAN","HELMET BLUEPRINT"},
    {"Tower II","Sabotage","HIKOU","BLUEPRINT"},
    {"Tower II","Sabotage","BRONCO","BLUEPRINT"},
    {"Tower II","Sabotage","VOLT","CHASSIS BLUEPRINT"},
    {"Tower II","Sabotage","HIKOU","POUCH"},
    {"Tower II","Sabotage","TRINITY","HELMET BLUEPRINT"},
    {"Tower III","Sabotage","NYX","BLUEPRINT"},
    {"Tower III","Sabotage","FORMA","BLUEPRINT"},
    {"Tower III","Sabotage","SCINDO","BLADE"},
    {"Tower III","Sabotage","NOVA","HELMET BLUEPRINT"},
    {"Tower III","Sabotage","BRONCO","BARREL"},
    {"Tower III","Sabotage","SOMA","BARREL"},
    {"Tower III","Sabotage","VAUBAN","BLUEPRINT"},
    {"Tower III","Sabotage","FORMA",""},
    {"Tower IV","Sabotage","AKSTILETTO","RECEIVER"},
    {"Tower IV","Sabotage","NYX","SYSTEMS BLUEPRINT"},
    {"Tower IV","Sabotage","CARRIER","SYSTEMS"},
    {"Tower IV","Sabotage","FORMA","BLUEPRINT"},
    {"Tower IV","Sabotage","FRAGOR","HEAD"},
    {"Tower IV","Sabotage","KAVASA","BAND"},
    {"Tower IV","Sabotage","ASH","HELMET BLUEPRINT"},
    {"Tower IV","Sabotage","NOVA","HELMET BLUEPRINT"},
    {"Tower I","Survival A","BURSTON","BARREL"},
    {"Tower I","Survival A","ODONATA","SYSTEMS BLUEPRINT"},
    {"Tower I","Survival C","SCINDO","HANDLE"},
    {"Tower I","Survival C","PARIS","UPPER LIMB"},
    {"Tower I","Survival C","VOLT","SYSTEMS BLUEPRINT"},
    {"Tower I","Survival C","PARIS","LOWER LIMB"},
    {"Tower I","Survival C","BURSTON","STOCK"},
    {"Tower I","Survival C","NOVA","HELMET BLUEPRINT"},
    {"Tower II","Survival A","AKBRONCO","BLUEPRINT"},
    {"Tower II","Survival A","PARIS","LOWER LIMB"},
    {"Tower II","Survival A","FORMA","BLUEPRINT"},
    {"Tower II","Survival B","SOMA","BLUEPRINT"},
    {"Tower II","Survival B","FANG","BLADE"},
    {"Tower II","Survival B","HIKOU","BLUEPRINT"},
    {"Tower II","Survival C","BURSTON","RECEIVER"},
    {"Tower II","Survival C","SOMA","RECEIVER"},
    {"Tower II","Survival C","PARIS","BLUEPRINT"},
    {"Tower II","Survival C","ASH","CHASSIS BLUEPRINT"},
    {"Tower II","Survival C","NIKANA","BLADE"},
    {"Tower II","Survival C","BRONCO","BLUEPRINT"},
    {"Tower II","Survival C","TRINITY","CHASSIS BLUEPRINT"},
    {"Tower III","Survival A","FANG","BLUEPRINT"},
    {"Tower III","Survival A","FANG","BLADE"},
    {"Tower III","Survival B","VECTIS","BARREL"},
    {"Tower III","Survival B","LEX","BARREL"},
    {"Tower III","Survival B","VOLT","HELMET BLUEPRINT"},
    {"Tower III","Survival C","LEX","BLUEPRINT"},
    {"Tower III","Survival C","CARRIER","BLUEPRINT"},
    {"Tower III","Survival C","VAUBAN","SYSTEMS BLUEPRINT"},
    {"Tower III","Survival C","ASH","SYSTEMS BLUEPRINT"},
    {"Tower III","Survival C","SARYN","CHASSIS BLUEPRINT"},
    {"Tower III","Survival C","DUAL KAMAS","BLUEPRINT"},
    {"Tower III","Survival C","NOVA","CHASSIS BLUEPRINT"},
    {"Tower III","Survival C","FORMA",""},
    {"Tower IV","Survival A","ASH","CHASSIS BLUEPRINT"},
    {"Tower IV","Survival A","DUAL KAMAS","BLUEPRINT"},
    {"Tower IV","Survival B","ORTHOS","BLUEPRINT"},
    {"Tower IV","Survival B","BRONCO","RECEIVER"},
    {"Tower IV","Survival B","LEX","BARREL"},
    {"Tower IV","Survival C","AKSTILETTO","LINK"},
    {"Tower IV","Survival C","BRATON","BLUEPRINT"},
    {"Tower IV","Survival C","FORMA","BLUEPRINT"},
    {"Tower IV","Survival C","ODONATA","WINGS BLUEPRINT"},
    {"Tower IV","Survival C","VASTO","BLUEPRINT"},
    {"Tower IV","Survival C","ASH","HELMET BLUEPRINT"},
    {"Derelict","Defense C","TRINITY","BLUEPRINT"},
    {"Derelict","Defense C","DUAL KAMAS","HANDLE"},
    {"Derelict","Defense C","SOMA","STOCK"},
    {"Derelict","Defense C","FORMA","BLUEPRINT"},
    {"Derelict","Survival C","BURSTON","BARREL"},
    {"Derelict","Survival C","NOVA","SYSTEMS BLUEPRINT"},
    {"Derelict","Survival C","FORMA","BLUEPRINT"},
},
}